# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /:title/

# Setup
title:            Advanced Foss Blog
tagline:          ''
description:      ''
url:              http://citruspi.github.io/advfoss-blog
baseurl:		  /advfoss-blog

author:
  name:           'citruspi'
  url:            http://citruspi.io

paginate:         100

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/citruspi/advfoss-blog
